let vm = new Vue({
    el: '#main',
    data: {
        //user:{},
        //roles: [],
        tarea: [],
        accion:''
    },
    methods: {
        /**boton de modal Guardar*/
        guardarUser: function () {
            if (vm.accion=='nuevo') {
                Tareas.store();
            } else {
                Tareas.update(vm.tarea.id);
            }
        },
        /**boton llama a modal, nuevo user */
        storeUser: function () {
            $("#modal-tarea").modal();
            vm.accion = 'nuevo';
            vm.tarea = {};
            $selectRoles.val([]).trigger("change");
        },
        roles: function(){
            Roles.all();
        },
    },
});

var tabla='tabla_registro_tarea';

/* BASIC ;*/
var responsiveHelper_datatable_tabletools = undefined;

var $selectRoles;

var breakpointDefinition = {
    tablet : 1024,
    phone : 480
};

var columns=[
    {
        data: "TaskNumber",
        name: "TaskNumber",
        searchable:false
    },
    {
        data: "EmployeeNumber",
        name: "EmployeeNumber",
        searchable:false
    },
    {
        data: "trabajador",
        name: "trabajador",
        searchable:false
    },
    {
        data: "Description",
        name: "Description",
        searchable:false
    },
    {
        data: "tipo",
        name: "tipo",
        searchable:false
    },
    {
        data: "estado",
        name: "estado",
        searchable:false
    },
    {
        name: "created_at",
        searchable:false,
        data: function ( row, type, val, meta ) {
            return '<td><button type="button" onClick="editar('+row.id+')" class="btn btn-primary">Editar</button></td>';
        },
        "defaultContent": '',
    },
    {
        name: "deleted_at",
        searchable:false,
        data: function ( row, type, val, meta ) {
            estado='<button type="button"  onClick="activar('+row.id+')" class="btn btn-success">Inactivo</button>';
            if (row.deleted_at===null){
                estado='<button type="button" onClick="desactivar('+row.id+')" class="btn btn-success">Activo</button>';
            }
            return estado;
        },
        defaultContent: '',
    }
];
var url = "api/tareas";
var tableTools = {
    "aButtons": [
        "copy",
        "csv",
        "xls",
        {
            "sExtends": "pdf",
            "sTitle": "SmartAdmin_PDF",
            "sPdfMessage": "SmartAdmin PDF Export",
            "sPdfSize": "letter"
        },
        {
            "sExtends": "print",
            "sMessage": "Generated by SmartAdmin <i>(press Esc to close)</i>"
        }
    ],
    "sSwfPath": "js/plugin/datatables/swf/copy_csv_xls_pdf.swf"
};
var dataTable={
    "processing": true,
    "serverSide": true,
    "stateSave": true,
    "searching": true,
    "ordering": true,
    "stateLoadCallback": function (settings) {
        //$("body").append('<div class="overlay"></div><div class="loading-img"></div>');
    },
    "stateSaveCallback": function (settings) { // Cuando finaliza el ajax
        //$(".overlay,.loading-img").remove();
    },
    ajax: function(data, callback, settings) {
        Tareas.getAll(data,callback);
    },
    "columns":columns,
    "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'T>r>"+
            "t"+
            "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
    "oLanguage": {
        "sSearch": '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>'
    },
    "oTableTools": tableTools,
    "autoWidth" : true,
    "preDrawCallback" : function() {
        // Initialize the responsive datatables helper once.
        if (!responsiveHelper_datatable_tabletools) {
            responsiveHelper_datatable_tabletools = new ResponsiveDatatablesHelper($('#'+tabla), breakpointDefinition);
        }
    },
    "rowCallback" : function(nRow,data) {
        responsiveHelper_datatable_tabletools.createExpandIcon(nRow);
    },
    "drawCallback" : function(oSettings) {
        responsiveHelper_datatable_tabletools.respond();
    }
};
var datatable;
$(document).ready(function() {
    pageSetUp();
    //Roles.all();
    datatable = $('#'+tabla).DataTable(dataTable);
});
/**
   
*/
editar=function(id){
    vm.accion='editar';
    Tareas.get(id);
    $("#modal-tarea").modal();
};
desactivar=function(id){
    reload();
};
activar=function(id){
    reload();
};
reload=function(){
    datatable.ajax.reload(null,false);
};
/*
roles=function(){
    var rolesUser=[];
    for ( i = vm.user.roles.length - 1; i >= 0; i--) {
        rolesUser.push(vm.user.roles[i].id);
    }
    $selectRoles.val(rolesUser).trigger("change");
};*/